config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "figures#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :figures, only: [:index, :new, :create, :edit, :show, :destroy] do
    resources :orders, only: [:new, :create,]
  end
  resources :users, only: [:show]
  resources :orders, only: [:index,:show] do
    resources :reviews, only: [:new, :create]
  end
  resources :animes, only: [:index, :show]
  get 'search', to: 'animes#search', as: 'search'
  get 'animes/autocomplete', to: 'animes#autocomplete', as: 'autocomplete_animes'

  namespace :purchased do
    resources :figures, only: :index
    # equivalent to => get 'translator/bookings', to: 'translator/bookings#index'
  end

  namespace :listed do
    resources :figures, only: :index
  end

  patch "orders/:id", to: "orders#update", as: :update_order
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :orders

  #validations
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :pick_up, inclusion: { in: [true, false] }
  validates :delivery, inclusion: { in: [true, false] }
  has_many_attached :photos

  validates :pick_up_location, presence: true, if: :pick_up?

  def pick_up?
    pick_up
  end

  validate :at_least_one_delivery_option

  def at_least_one_delivery_option
    if !pick_up && !delivery
      errors.add(:pick_up, "must be selected or")
      errors.add(:delivery, "must be selected")
    end
  end
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    #sort figures by created_at in descending order
    @figures = Figure.all.order(created_at: :desc)
    @animes = Anime.all
  end

  def new
    @figure = Figure.new
  end

  def create
    @figure = Figure.create(figure_params)
    @figure.user = current_user
    if @figure.save
      # redirect_to list_path(@list)
      redirect_to listed_figures_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @figure = Figure.find(params[:id])
    review_arr = Review.where(reviewee: @figure.user)
    @user_rating = review_arr.map {|rev| rev.rating}.sum / review_arr.count
    @order = Order.new
  end

  def edit
    @figure = Figure.find(params[:id])
  end

  def update
    @figure = Figure.find(params[:id])
    if @figure.update(figure_params)
      redirect_to listed_figures_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
      puts "hello world"
      @figure = Figure.find(params[:id])
      @figure.destroy
      redirect_to listed_figures_path
    end

  private

  def figure_params
    params.require(:figure).permit(:name, :description, :price, :anime_id, :pick_up, :pick_up_location, :delivery, photos: [])
  end

end

app/controllers/listed/figures_controller.rb
class Listed::FiguresController < ApplicationController
  def index
    # Figure.user_id == current_user.id
    @orders = Order.all
    # display figures in descending created_at order
    @figures = Figure.all.order(created_at: :desc)

    # collects all orders that match the current logged in user's ID for display
    @order_sales = @orders.select do |order|
      order.figure.user.id == current_user.id
    end

    # collects all figures that match the current logged in user's ID for display
    @user_figures = @figures.select do |figure|
      figure.user.id == current_user.id
    end

    # collects all reviews that match the current logged in user's ID for display
    @user_reviews = Review.all.select do |review|
      review.reviewee.id == current_user.id
    end
  end
end

app/controllers/purchased/figures_controller.rb
class Purchased::FiguresController < ApplicationController
  def index
    @orders = Order.all.select { |order| order.buyer == current_user }
    # @favorite_figures =
    @reviewed_products = Review.all.select { |review| review.reviewer == current_user }
    @unreviewed_products = @orders.select { |order| order.reviews.empty? }
  end
end

app/views/listed/figures/_order_list.html.erb
<% orders.each_with_index do |order, index| %>
  <div class="card mb-3" style="height: fit-content;">
    <div class="order-card d-flex bg-light" data-bs-toggle="collapse" href="#collapse<%= index %>" role="button" aria-expanded="false" aria-controls="collapse<%= index %>" data-controller="toggle" data-action="click->toggle#toggle">
      <p class="card-title flex-grow-1 ps-1">
        <span class="weak-font">#<%= order.id %></span> - <%= order.figure.name %>
        <span class="status-icon"><i class="fa-solid fa-truck"></i> <%= order.status == "pending" ? "awaiting shipment" : order.status %></span>
      </p>
      <% if order.figure.user == current_user %>
        <% if order.status == 'pending' %>
          <div class="d-flex mt-2 me-2">
            <%= button_to "Complete", update_order_path(order), method: :patch, params: { order: { status: 'completed', mode_of_delivery: order.mode_of_delivery } }, class: "btn btn-outline-success btn-sm me-2" %>
            <%= button_to "Cancel", update_order_path(order), method: :patch, params: { order: { status: 'cancelled', mode_of_delivery: order.mode_of_delivery } }, class: "btn btn-outline-danger btn-sm" %>
          </div>
        <% end %>
      <% end %>

      <div class="chevron-toggle my-auto pe-2">
        <i class="fa fa-chevron-up" data-toggle-target="icon"></i>
      </div>
    </div>

    <div class="collapse multi-collapse-orders p-3 bg-light " id="collapse<%= index %>">
      <p class="card-text"><i class="fa-solid fa-person"></i> <%= order.buyer.username %> #<%= order.buyer.id %> </p>

      <p class="card-text"><i class="fa-solid fa-video"></i> <%= order.figure.anime.title %></p>

      <p class="card-text"><i class="fa-solid fa-yen-sign"></i><%= order.figure.price %></p>

      <p class="card-text">
        <i class="fa-solid fa-location-dot"></i>
        <% if order.figure.pick_up %>
          <%= order.figure.pick_up_location %>
        <% else %>
          <%= order.mode_of_delivery %>
        <% end %>
      </p>

      <% if order.buyer == current_user %>
        <% if order.reviews.empty? %>
          <%= link_to "Review", new_order_review_path(order), class: "btn btn-primary float-end" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/listed/figures/_product_list.html.erb
<%= link_to "+ Add new figure", new_figure_path, class: "btn m-3"%>
<% figures.each do |figure| %>
  <div class="card figure-card p-3 mb-3">
    <h6><strong>Figure ID #<%= figure.id %> - <%= figure.name %></strong> <em>(<%= figure.anime.title %>)</em></h6>
    <div class="d-flex">
      <div class="image-container me-3" style="background-image: url(<%= figure.photos.any? ? cl_image_path(figure.photos.first.key) : image_path('logo.png')%>)"></div>
      <div class="figure-info d-flex flex-column justify-content-between w-100">
        <p class="mb-1"><%= figure.description %></p>
        <p class="mb-1"><strong>¥</strong> <%= figure.price %></p>
        <div class="flex-grow-1">
          <p class="m-0"><strong>Delivery options:</strong></p>
          <% if figure.pick_up %>
            <p class="m-0"><i class="fa-regular fa-square-check"></i> Pick-up at <%= figure.pick_up_location %></p>
          <% end %>
          <% if figure.delivery %>
            <p><i class="fa-regular fa-square-check"></i> Delivery</p>
          <% end %>
        </div>
        <div class="d-flex justify-content-between">
          <p class="text-muted"><em>Posted at <%= figure.created_at %></em></p>
          <% if figure.orders.any? { |order| order.status == 'pending' } %>
            <p><em>awaiting shipment</em></p>
          <% elsif figure.orders.any? { |order| order.status == 'completed' }  %>
            <p><em>shipped</em></p>
          <% else %>
            <% if figure.user == current_user %>
              <%= link_to "Edit", edit_figure_path(figure), class: "btn me-3"%>
              <%= link_to "Delete figure", figure_path(figure), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this figure?" }, class: "btn btn-danger me-3", style: "background-color: red;" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/listed/figures/_review_list.html.erb
<% reviews.each do |review| %>
  <div class="card p-3 mb-3 bg-white">
    <div class="d-flex">
      <% review.rating.times do %>
        <h6><i class="fa-solid fa-star me-1 mb-3"></i></h3>
      <% end %>
    </div>
    <h4 class="font-weight-bold">Order#<%= review.order.id %> - <%= review.order.figure.name %></h4>
    <p class="card-text">"<%= review.comment %>"</p>

    <div class="reviewer-info d-flex">
      <% if review.reviewer.photo.attached? %>
        <%= cl_image_tag review.reviewer.photo.key, class: "avatar me-3" %>
      <% else %>
        <%= image_tag "logo.png", class: "avatar me-3" %>
      <% end %>
      <div>
        <p class="text-muted m-0"><%= review.order.buyer.username %></p>
        <p class="text-muted"><%= review.created_at.to_date %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/listed/figures/index.html.erb
<div class="p-4" data-controller="toggle">
  <div class="d-flex">
    <div>
      <div class="d-flex justify-content-around me-3 my-2 sb-container">
        <%= link_to listed_figures_path, class: "text-decoration-none" do %>
          <p class="mx-2 bg-dark text-light">Seller</p>
        <% end %>
        <%= link_to purchased_figures_path, class: "text-decoration-none" do %>
          <p class="mx-2">Buyer</p>
        <% end %>
      </div>
      <div class="dashboard-side-menu card p-2 mt-1 me-3" >
        <div class="menu-item d-flex px-3 py-2 mt-3 mb-1" data-action="click->toggle#order" data-toggle-target="orderList">
          <i class="fa-solid fa-bag-shopping me-3"></i>
          <p>Sale Orders</p>
        </div>
        <div class="menu-item d-flex px-3 py-2 mb-1" data-action="click->toggle#product" data-toggle-target="productList">
          <i class="fa-solid fa-tag me-3"></i>
          <p>Products</p>
        </div>
        <div class="menu-item d-flex px-3 py-2 mb-1" data-action="click->toggle#review" data-toggle-target="reviewList">
          <i class="fa-solid fa-star me-3"></i>
          <p>Reviews</p>
        </div>
      </div>
    </div>
    <div class="dashboard-content col-7 mt-1">
      <div class="blank-space">
      </div>
      <div data-toggle-target="orderButton" class="order-container">
        <%= render "order_list", orders: @order_sales %>
      </div>
      <div data-toggle-target="productButton" class="product-container">
        <%= render "product_list", figures: @user_figures %>
      </div>
      <div data-toggle-target="reviewButton" class="review-container">
        <%= render "review_list", reviews: @user_reviews %>
      </div>
    </div>
  </div>
</div>