config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "figures#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :figures, only: [:index, :new, :create, :edit, :show, :destroy] do
    resources :orders, only: [:new, :create,]
  end
  resources :users, only: [:show]
  resources :orders, only: [:index,:show] do
    resources :reviews, only: [:new, :create]
  end
  resources :animes, only: [:index, :show]
  get 'search', to: 'animes#search', as: 'search'
  get 'animes/autocomplete', to: 'animes#autocomplete', as: 'autocomplete_animes'

  namespace :purchased do
    resources :figures, only: :index
    # equivalent to => get 'translator/bookings', to: 'translator/bookings#index'
  end

  namespace :listed do
    resources :figures, only: :index
  end

  patch "orders/:id", to: "orders#update", as: :update_order
end

app/models/figure.rb
class Figure < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :orders

  #validations
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :pick_up, inclusion: { in: [true, false] }
  validates :delivery, inclusion: { in: [true, false] }
  has_many_attached :photos

  validates :pick_up_location, presence: true, if: :pick_up?

  def pick_up?
    pick_up
  end

  validate :at_least_one_delivery_option

  def at_least_one_delivery_option
    if !pick_up && !delivery
      errors.add(:pick_up, "must be selected or")
      errors.add(:delivery, "must be selected")
    end
  end
end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    #sort figures by created_at in descending order
    @figures = Figure.all.order(created_at: :desc)
    @animes = Anime.all
  end

  def new
    @figure = Figure.new
  end

  def create
    @figure = Figure.create(figure_params)
    @figure.user = current_user
    if @figure.save
      # redirect_to list_path(@list)
      redirect_to listed_figures_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @figure = Figure.find(params[:id])
    review_arr = Review.where(reviewee: @figure.user)
    @user_rating = review_arr.map {|rev| rev.rating}.sum / review_arr.count
    @order = Order.new
  end

  def edit
    @figure = Figure.find(params[:id])
  end

  def update
    @figure = Figure.find(params[:id])
    if @figure.update(figure_params)
      redirect_to listed_figures_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
      puts "hello world"
      @figure = Figure.find(params[:id])
      @figure.destroy
      redirect_to listed_figures_path
    end

  private

  def figure_params
    params.require(:figure).permit(:name, :description, :price, :anime_id, :pick_up, :pick_up_location, :delivery, photos: [])
  end

end

app/controllers/listed/figures_controller.rb
class Listed::FiguresController < ApplicationController
  def index
    # Figure.user_id == current_user.id
    @orders = Order.all
    # display figures in descending created_at order
    @figures = Figure.all.order(created_at: :desc)

    # collects all orders that match the current logged in user's ID for display
    @order_sales = @orders.select do |order|
      order.figure.user.id == current_user.id
    end

    # collects all figures that match the current logged in user's ID for display
    @user_figures = @figures.select do |figure|
      figure.user.id == current_user.id
    end

    # collects all reviews that match the current logged in user's ID for display
    @user_reviews = Review.all.select do |review|
      review.reviewee.id == current_user.id
    end
  end
end

app/controllers/purchased/figures_controller.rb
class Purchased::FiguresController < ApplicationController
  def index
    @orders = Order.all.select { |order| order.buyer == current_user }
    # @favorite_figures =
    @reviewed_products = Review.all.select { |review| review.reviewer == current_user }
    @unreviewed_products = @orders.select { |order| order.reviews.empty? }
  end
end

app/views/figures/_anime-category-cards.erb
<div class="d-flex justify-content-between container my-3">
  <% @animes.each do |anime| %>
    <%= link_to anime_path(anime), class: "text-decoration-none" do %>
      <% img = anime.photo.attached? ? cl_image_path(anime.photo.key) : image_path('logo.png') %>
      <div class="anime-card bg-image hover-zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img %>)" >
        <%= anime.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/figures/_banner.html.erb
<div class="banner mt-1" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://res.cloudinary.com/dckq0zged/image/upload/v1721401284/fdffixllexjztex4ystr.webp);">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="banner-title">Welcome to Ara-Ara</h1>
        <p class="banner-text">The best place to find and share your favorite figures</p>
        <%# <a class="btn btn-light" href="">Sell Now</a> %>
        <%= link_to "Sell Now", new_figure_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>

app/views/figures/_form.html.erb
<%= simple_form_for figure do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.association :anime %>
    <div class="d-flex">
      <%= f.input :pick_up, as: :boolean, label_html: { class: "me-3"} %>
      <%= f.input :delivery, as: :boolean %>
    </div>
    <%= f.input :pick_up_location%>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit btn_text %>
  <% end %>

app/views/figures/edit.html.erb
<div class="container w-50 shadow-sm p-3 mb-5 bg-white rounded">
  <%= render 'form', figure: @figure, btn_text: "Update Figure" %>
</div>

app/views/figures/index.html.erb
<%= render 'shared/anime-category-cards' %>
<%= render 'banner' %>
<div class="container mt-4">
  <h1 class="mb-3"><%= "Anime figures (#{@figures.count})" %></h1>
  <div class="content-container">
    <div class="figures-container">
      <%= render 'shared/figure_card' %>
    </div>
  </div>
</div>

app/views/figures/new.html.erb
<div class="container w-50 shadow-sm p-3 mb-5 bg-white rounded">
  <%= simple_form_for @figure do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.association :anime %>
    <div class="d-flex">
      <%= f.input :pick_up, as: :boolean, label_html: { class: "me-3"} %>
      <%= f.input :delivery, as: :boolean %>
    </div>
    <%= f.input :pick_up_location%>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Add Figure" %>
  <% end %>
</div>

app/views/figures/show.html.erb
<div class="d-flex mx-4 my-5 row">
  <div class="figure-photos col-4">
    <div class="big-figure-img" style="height: 500px; background-image: url(<%= @figure.photos.any? ? cl_image_path(@figure.photos.first.key) : image_path('logo.png') %>)">
    </div>

    <% if @figure.photos.count > 1 %>
      <div class="d-flex mt-3 justify-content-between">
        <% @figure.photos.each do |photo| %>
          <div class="small-figure-img" style="height: 150px; width: 120px; background-image: url(<%= cl_image_path(photo.key) %>)" data-controller="image-toggler" data-action="click->image-toggler#changeBigImage"></div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="figure-info mx-4 col-4">
    <h3 class="fw-bold mt-3"><%= @figure.name %></h3>
    <div class="reviewer-info d-flex">
      <% if @figure.user.photo.attached? %>
        <%= link_to user_path(@figure.user) do %>
          <%= cl_image_tag @figure.user.photo.key, class: "avatar me-3" %>
        <% end %>
      <% else %>
        <%= link_to user_path(@figure.user) do %>
          <%= image_tag "logo.png", class: "avatar me-3" %>
        <% end %>
      <% end %>
      <div>
        <p class="text-muted m-0"><%= @figure.user.username %></p>
        <p class="text-muted"><em>Average </em><i class="fa-solid fa-star"></i>: <%= @user_rating%></p>
      </div>
    </div>
    <h1 class="fw-bold">¥ <%= @figure.price %></h1>
    <p class="text-muted"><%= @figure.description %></p>
    <p class="m-0"><strong>Delivery options:</strong></p>
    <% if @figure.pick_up %>
      <p class="m-0"><i class="fa-regular fa-square-check"></i> Pick-up at <%= @figure.pick_up_location %></p>
    <% end %>
    <% if @figure.delivery %>
      <p><i class="fa-regular fa-square-check"></i> Delivery</p>
    <% end %>
  </div>

  <div class="checkout card p-4 col-3" style="height: fit-content;">
    <h3 class="fw-bold mb-3">Checkout Information</h3>
    <% available_options = [] %>
    <% available_options << ["Pick up at #{@figure.pick_up_location}", "pickup"] if @figure.pick_up %>
    <% available_options << ["Deliver to my address", "delivery"] if @figure.delivery %>

    <%= simple_form_for [@figure, @order] do |f| %>
      <label for="full_name">Full Name</label>
      <input type="text" id="full_name" class="form-control mb-3" readonly value="<%= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}" %>">
      <label for="figure_name">Figure</label>
      <input id="figure_name" class="form-control mb-3" type="text" placeholder="<%= @figure.name %>" readonly>
      <%= f.input :mode_of_delivery, as: :radio_buttons, collection: available_options %>
      <%= hidden_field_tag :figure_id, @figure.id %>
      <label for="billing">Billing/ Card info</label>
      <input type="text-area" id="billing" class="form-control mb-3">
      <%= f.submit 'Buy Now', class: "btn btn-primary mt-3 w-100" %>
    <% end %>
  </div>
</div>