config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "figures#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :figures, only: [:index, :new, :create, :edit, :show, :destroy] do
    resources :orders, only: [:new, :create,]
  end
  resources :users, only: [:show]
  resources :orders, only: [:index,:show] do
    resources :reviews, only: [:new, :create]
  end
  resources :animes, only: [:index, :show]
  get 'search', to: 'animes#search', as: 'search'
  get 'animes/autocomplete', to: 'animes#autocomplete', as: 'autocomplete_animes'

  namespace :purchased do
    resources :figures, only: :index
    # equivalent to => get 'translator/bookings', to: 'translator/bookings#index'
  end

  namespace :listed do
    resources :figures, only: :index
  end

  patch "orders/:id", to: "orders#update", as: :update_order
end

app/views/shared/_anime-category-cards.html.erb
<div class="d-flex justify-content-between container my-3">
  <% @animes.each do |anime| %>
    <%= link_to anime_path(anime), class: "text-decoration-none" do %>
      <% img = anime.photo.attached? ? cl_image_path(anime.photo.key) : image_path('logo.png') %>
      <div class="anime-card bg-image hover-zoom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img %>)" >
        <%= anime.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_card-product.html.erb
<div class="container">
  <h1>All Figures</h1>
  <div class="row">
    <% @figures.each do |figure| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= figure.name %></h5>
            <p class="card-text">Price: <%= figure.price %></p>
            <p class="card-text">Description: <%= figure.description%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_figure_card.html.erb
<% @figures.each_with_index do |figure, index| %>
  <div class="all-figures-card" style="max-width: 21rem; height: fit-content;">
    <div class="small-card" data-bs-toggle="collapse" href="#collapse<%= index %>" role="button" aria-expanded="false" aria-controls="collapse<%= index %>" data-controller="toggle" data-action="click->toggle#toggle">
      <div class="d-flex justify-content-between align-items-center">
        <div class="small-card-text">
          <h5 class="figure-name"><%= figure.name %></h5>
          <p class="figure-price">¥ <%= figure.price %></p>
        </div>
        <div class="chevron-toggle">
          <i class="fa fa-chevron-up" data-toggle-target="icon"></i>
        </div>
      </div>
      <div class="img-container">
        <%= image_tag figure.photos.first, class: "figure-img" if figure.photos.any? %>
      </div>
    </div>
    <div class="collapse multi-collapse" id="collapse<%= index %>">
      <div class="collapse-card">
        <p class="figure-description"><%= figure.description %></p>
        <div class="figure-card-bottom">
          <% if figure.orders.any? { |order| order.status == 'completed' } %>
            <p class="figure-sold">SOLD</p>
          <% elsif figure.orders.any? { |order| order.status == 'pending' } %>
            <p class="figure-hold">ON HOLD</p>
          <% elsif figure.user == current_user %>
            <p class="figure-owned">OWNED</p>
          <% else %>
            <%= link_to 'Buy Now', figure_path(figure), class: 'btn btn-primary' %>
          <% end %>
          <h5 class="anime-name"><%= figure.anime.title %></h5>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made by <i class="fas fa-heart"></i> Brian Inphouva, Aya Fujita, Ikumi Ojiro, and Javier Ruiz.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "http://res.cloudinary.com/dckq0zged/image/upload/v1721397806/kjobiobwr9xclwijmyhi.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex justify-content-center searchbar-homepage">
      <div id="cover">
        <%= form_with url: search_path, method: :get, local: true do %>
          <div class="tb">
            <div class="td">
              <%= text_field_tag :query, params[:query], placeholder: "Search", required: true, id: "search-input" %>
            </div>
            <div class="td" id="s-cover">
              <button type="submit">
                <div id="s-circle"></div>
                <span></span>
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <div class="anime_search">
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", listed_figures_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>